spring:
  application:
    name: healthcare-dsa-service
  profiles:
    active: h2
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        default_schema: dsa_healthcare_db
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true


  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

management:
  endpoints:
    web:
      exposure:
        include: "*"

