spring:
  config:
    activate:
      on-profile: h2

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        default_schema: dsa_healthcare_db

  h2:
    console:
      enabled: true
      path: /h2-console